apiVersion: batch/v1
kind: CronJob
metadata:
  name: profile-history-service-cron-production
spec:
  schedule: "0 22 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: profile-history-service-cron-production
            image: refx-online/profile-history-service:latest
            imagePullPolicy: Always
            command:
              - ./scripts/bootstrap.sh
            env:
              - name: KUBERNETES
                value: 'true'
              - name: PULL_SECRETS_FROM_VAULT
                value: '1'
              - name: VAULT_ADDR
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: address
              - name: VAULT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: token
              - name: APP_ENV
                value: production # TODO
              - name: APP_COMPONENT
                value: crawler-cronjob
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: refx-registry-secret
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
